In [20]:
from more_itertools import flatten

from sphere import spherex
import numpy as np
# User inputid are: fitness function, lowerbound(lb),upperbound(ub), populatonsize(N_p)
#number of iterations(T), scaling factor F, crossover probability(P_c)


#problem settings
lb = np.array([0,0,0,0,0])
ub = np.array([10,10,10,10,10])


#Paramaters for Differential Evlution

N_p = 5 #Number of population
T = 93 #number of iterations
P_c = 0.8 #crossover probability
F = 0.85 #scaling factor




In [21]:
#Initializing DE
f = np.zeros((N_p,1)) #empty vector for fitness function

fu = np.zeros((N_p,1))#newly created trial vector

D = len(lb) # Determining amount of decision variables

U = np.zeros((N_p,D)) #Matrix for storing trial solutions 

print(U)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [22]:
import numpy.matlib as mat
#Initial random population !!!!!MIND THE "LEN", I DONT KNOW if that works"
P = mat.repmat(lb,N_p,1)+mat.repmat((ub-lb),N_p,1)*np.random.rand(len(ub-lb),N_p)

print(P)

[[9.31253071 7.74860361 2.57509656 4.8025126  7.25375969]
 [0.84968885 8.36258081 3.68402645 9.61106889 8.84553425]
 [4.64785648 5.10508957 8.83200229 8.11336788 8.24698228]
 [6.13753439 5.14722002 7.15130708 7.46376648 9.56184284]
 [9.54903713 6.3070603  8.38830321 3.88612077 7.30100703]]


In [23]:
#initial fitness function values to f as a vector #1


#import numpy as np
#for i, p in enumerate(np.arange(N_p)):
#        f_p =spherex(P[p,])
 #       f[i] = f_p
#        #print(f_p)
#print(f)

#print(np.arange(N_p))
#print(range(N_p))

In [24]:
#initial fitness function values to f as a vector
for p in np.arange(N_p):
    f[p]=spherex(P[p,])
print(f)
#i =1 
#print(np.arange(N_p)[0:i-1 and i+1:N_p])
#print([i for i in np.arange(N_p) if i==i])



[[229.07636533]
 [254.84290102]
 [259.50822885]
 [262.4410438 ]
 [269.73338871]]


In [46]:
#iteration loop
for t in np.arange(T):
    
    for i in np.arange(N_p):
        
        
        
        #MUTATION
        #candidates are assigned without the i-th element
        candidates= np.delete(np.arange(N_p), np.where(np.arange(N_p)==i))
        #3 target vectors are picked out randomly for the donorvector generator
        cand_rand=np.random.choice(candidates,3,replace= False)
        X1=P[cand_rand[0],]
        X2=P[cand_rand[1],]
        X3=P[cand_rand[2],]
        #Donorvctor generator
        V= X1 + F*(X2-X3)
        
        
        #Crossover
        delta = np.random.randint(0,D-1) 
        for j in np.arange(D):
            if np.random.uniform(0,1) <= P_c or delta == j:
                U[i,j] = V[j]
            else:
                U[i,j]=P[i,j]
                
        
       ##Bounding and Greedy Selection

    for j in np.arange(N_p):
        U[j]=np.minimum(U[j], ub)
        U[j]=np.maximum(U[j], lb)
    
        fu[j]=spherex(U[j])
    
        if fu[j] < f[j]:
            P[j]= U[j]
            f[j]=fu[j]
 
        
        
        
        
        
        
        

print(f'Final iteration results for P:\n{ P}')
print(f'Fitness function values{f}')
best_of_f= min(f)
print(f'Best fitness function value{best_of_f}')
print(f'Best fitness value location/row {f.argmin()}')
print(f'Best solution {P[f.argmin()]}')

Final iteration results for P:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Fitness function values[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Best fitness function value[0.]
Best fitness value location/row 0
Best solution [0. 0. 0. 0. 0.]


In [32]:
#best solution

In [8]:
##Bounding and Greedy Selection

for j in np.arange(N_p):
    U[j]=np.minimum(U[j], ub)
    U[j]=np.maximum(U[j], lb)
    
    fu[j]=spherex(U[j])
    
    if fu[j] < f[j]:
        P[j]= U[j]
        f[j]=fu[j]



In [9]:
for j in np.arange(N_p):
    U[j]=np.minimum(U[j], ub)
    U[j]=np.maximum(U[j], lb)
    
print(U)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
    for i in np.arange(N_p):
         #MUTATION
        #candidates are assigned without the i-th element
        candidates= np.delete(np.arange(N_p), np.where(np.arange(N_p)==i))
        #3 target vectors are picked out randomly for the donorvector generator
        cand_rand=np.random.choice(candidates,3,replace= False)
        X1=P[cand_rand[0],]
        X2=P[cand_rand[1],]
        X3=P[cand_rand[2],]
        #Donorvctor generator
        V= X1 + F*(X2-X3)
        #Crossover
        print(V)
        

[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]


In [11]:
#delta = np.random.randint(0,D-1)
#print(delta)
#print(np.arange(D))

In [12]:
#Crossover
delta = np.random.randint(0,D-1) 
for j in np.arange(D):
    if np.random.uniform(0,1) <= P_c or delta == j:
        U[i,j] = V[j]
    else:
        U[i,j]=P[i,j]
        
    

print(P)
print(V)
print(U)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
print(P[2,3])

0.0
